# Generated by Django 3.2.2 on 2021-06-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('detail', models.CharField(max_length=384)),
                ('position', models.CharField(max_length=384)),
            ],
            options={
                'verbose_name': '影院',
                'verbose_name_plural': '影院',
                'ordering': ['cinema_id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cinema')),
            ],
            options={
                'verbose_name': '影厅',
                'verbose_name_plural': '影厅',
                'ordering': ['room_id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
            options={
                'verbose_name': '排期',
                'verbose_name_plural': '排期',
                'ordering': ['schedule_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_col', models.IntegerField()),
                ('seat_row', models.IntegerField()),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'verbose_name': '影票',
                'verbose_name_plural': '影票',
                'ordering': ['ticket_id'],
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('hy', '华语'), ('om', '欧美'), ('rh', '日韩'), ('dz', '动作'), ('xj', '喜剧'), ('aq', '爱情'), ('kh', '科幻'), ('xy', '悬疑'), ('kb', '恐怖'), ('wy', '文艺')], max_length=32)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['movie_id'],
            },
        ),
    ]
