# Generated by Django 3.2.2 on 2021-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('using', '待使用'), ('used', '已使用'), ('returned', '已退票')], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
