# Generated by Django 3.2.2 on 2021-06-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
